# Generated by Django 4.1.1 on 2022-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_time_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
